management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus

logging:
  level:
    com:
      meraj:
        MonitoringDemo: debug
